### ISSUE TITLE
question about FPS during attack

### ISSUE THREAD

**Issue by HXZhong1997** [VISION-SJTU/IoUattack#2]
Congrats on your brilliant work!

Out of curiosity, I've got one issue though about tracking FPS under your attack. The attacking process described in the paper seems to be time-consuming, as there are several predictions for one-frame. 
So can you share something like the FPS during attack? I'm really curious about that. ^_^

I just read the paper real quick, so plz correct me if I misunderstood anything. Thank you so much!

**Comment by joshuajss** [comment]
Thanks for your attention! Our decision-based method queries the trackers repeatedly during attack. Thus, the speed of our method mainly depends on the speed of tracker itself. We state that 'The average query numbers of IoU attack are 21.2, 31.4 and 54.2 per frame for SiamRPN++. DiMP and LTMU, respectively.' in our paper. I hope it can help you. :)

**Comment by HXZhong1997** [comment]
> Thanks for your attention! Our decision-based method queries the trackers repeatedly during attack. Thus, the speed of our method mainly depends on the speed of tracker itself. We state that 'The average query numbers of IoU attack are 21.2, 31.4 and 54.2 per frame for SiamRPN++. DiMP and LTMU, respectively.' in our paper. I hope it can help you. :)

Thx a lot. One more question ;)  does it mean that the tracking speed under attack is 20 times slower than in normal? take SiamRPN++ for example.

**Comment by joshuajss** [comment]
> > Thanks for your attention! Our decision-based method queries the trackers repeatedly during attack. Thus, the speed of our method mainly depends on the speed of tracker itself. We state that 'The average query numbers of IoU attack are 21.2, 31.4 and 54.2 per frame for SiamRPN++. DiMP and LTMU, respectively.' in our paper. I hope it can help you. :)
> 
> Thx a lot. One more question ;) does it mean that the tracking speed under attack is 20 times slower than in normal? take SiamRPN++ for example.

Yes. The time of each query is compulsive.

**Comment by HXZhong1997** [comment]
> > > Thanks for your attention! Our decision-based method queries the trackers repeatedly during attack. Thus, the speed of our method mainly depends on the speed of tracker itself. We state that 'The average query numbers of IoU attack are 21.2, 31.4 and 54.2 per frame for SiamRPN++. DiMP and LTMU, respectively.' in our paper. I hope it can help you. :)
> > 
> > 
> > Thx a lot. One more question ;) does it mean that the tracking speed under attack is 20 times slower than in normal? take SiamRPN++ for example.
> 
> Yes. The time of each query is compulsive.

OK I got this. Thank you so much for your patience~ 
I will close this issue now. :)
